name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run lint checks
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        with:
          command: lint --ignore clang-format

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build FAP
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        with:
          command: fap

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: i2c-tools-fap
          path: build/*/*.fap
          if-no-files-found: error
